version: '3.8'
services:
  bhive-app:
    image: sam1f100/bhive-app:latest
    ports:
      - "5000:80"
    labels:
      # Route base domain
      - "traefik.http.routers.bhive-app.rule=Host(`fk.bhivecommunity.co.uk`)"
      - "traefik.http.routers.bhive-app.tls=true"
      - "traefik.http.routers.bhive-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.bhive-app.loadbalancer.server.port=80"
      - "traefik.http.routers.https.entrypoints=https"

    networks:
      - traefik-letsencrypt-compose_default
  bhive-backend-sdk:
    image:   sam1f100/bhive-backend:latest
    ports:
      - "5001:3001"
    labels:
      - "traefik.http.routers.backend-sdk.rule=Host(`sdk.bhivecommunity.co.uk`)"
      - "traefik.http.routers.backend-sdk.tls=true"
      - "traefik.http.routers.backend-sdk.tls.certresolver=letsencrypt"
      - "traefik.http.routers.https.entrypoints=https"
      - "traefik.http.services.backend-sdk.loadbalancer.server.port=3001"
    networks:
      - traefik-letsencrypt-compose_default




networks:
  traefik-letsencrypt-compose_default:
    external: true

