name: Deploy to Docker Hub and Server

on:
  push:
    branches:
      - master
      - 1.2.0

jobs:
  build_and_push_images:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app Docker image
        run: |
          cd b-hive-app && docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bhive-app .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bhive-app
      - name: Build and push backend Docker image
        run: |
          cd backend && docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bhive-backend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bhive-backend